// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.abhi.hotelrewards


import scala.concurrent.Future


trait PlatinumWebServiceSoap {
  def dateTimeOnServer(): Future[com.abhi.hotelrewards.DateTimeOnServerResponse]
  def platinumRequest(astrXML: Option[String], astrError: Option[String]): Future[com.abhi.hotelrewards.PlatinumRequestResponse]
  def platinumRequest2(transactioN_XML: Option[String]): Future[com.abhi.hotelrewards.PlatinumRequest2Response]
}




