// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.abhi.hotelrewards


case class DateTimeOnServer()
      


case class DateTimeOnServerResponse(DateTimeOnServerResult: Option[String] = None)
      


case class PlatinumRequest(astrXML: Option[String] = None,
  astrError: Option[String] = None)
      


case class PlatinumRequestResponse(PlatinumRequestResult: Boolean,
  astrXML: Option[String] = None,
  astrError: Option[String] = None)
      


case class PlatinumRequest2(TRANSACTION_XML: Option[String] = None)
      


case class PlatinumRequest2Response(PlatinumRequest2Result: Option[String] = None)
      

